/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JTable;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmNotas extends javax.swing.JFrame {
    //variable memoria del tipo DefaultTableModel
    DefaultTableModel dtm = new DefaultTableModel();
    
    public frmNotas() {
        initComponents();
        //inicializamos los títulos de las columnas
        String titulos[] = {"Alumnos","Unidad I","Unidad II","Unidad III","Promedio","Turno"};
        //se define las columnas con sus respectivos titulos
        dtm.setColumnIdentifiers(titulos);
        //se vincula el modelo
        tablaResumen.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNotaI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNotaII = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNotaIII = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboTurno = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaResumen = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtTotalAlumnos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CALIFICACIONES DEL CURSO DE PROGRAMACIÓN VISUAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel2.setText("Alumno:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        getContentPane().add(txtAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, -1));

        jLabel3.setText("Nota de la Unidad I:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(txtNotaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, -1));

        jLabel4.setText("Nota de la Unidad II:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        getContentPane().add(txtNotaII, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 100, -1));

        jLabel5.setText("Nota de la unidad III:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 120, -1));
        getContentPane().add(txtNotaIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 110, -1));

        jLabel6.setText("Nota:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        cboTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Mañana", "Tarde", "Noche" }));
        getContentPane().add(cboTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        tablaResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaResumen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 360, 220));

        jLabel7.setText("Total de Alumnos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));
        getContentPane().add(txtTotalAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    //Obtendremos excepciones en caso no se ingresen notas o hayan ingresado letras
        try {    
            String datos[] = new String[6];
            int n1, n2, n3, total;
            double promedio;
            boolean verifica;
            //las variables reciben los valores ingresados
            n1 = Integer.parseInt(txtNotaI.getText());
            n2 = Integer.parseInt(txtNotaII.getText());
            n3 = Integer.parseInt(txtNotaIII.getText());

            /*evaluar si se llegó a escribir en el cuadro de nombre y también evaluamos 
                                                    si se llego a seleccionar un turno*/
            verifica = txtAlumno.getText().equals("")|| cboTurno.getSelectedIndex()==0;

            //si verfica es falso, ósea si tiene texto adentro y se seleccionó algo
            if(!verifica){
                //casteamos ya que arriba son int
                promedio = (double)(n1+n2+n3) / (double)3;
                //asignamos los datos ingresados y el turno seleccionado a cada posición
                datos[0] = txtAlumno.getText();
                datos[1] = txtNotaI.getText();
                datos[2] = txtNotaII.getText();
                datos[3] = txtNotaIII.getText();
                datos[4] = String.valueOf(promedio);
                datos[5] = (String)cboTurno.getSelectedItem();
                //creamos una fila con los valores contenidos del arreglo datos
                dtm.addRow(datos);
                //limpiamos los cuadros de texto
                txtAlumno.setText("");
                txtNotaI.setText("");
                txtNotaII.setText("");
                txtNotaIII.setText("");
                    //y lo dejamos en <Seleccionar> añ dar el valor 0 al metodo que está
                cboTurno.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null,"Falta el ingreso del nombre"
                                                             + " o seleccionar un turno");
            }

            //obtenemos la cantidad de filas agregadas en el cuadro
            total = dtm.getRowCount();
            //imprimimos
            txtTotalAlumnos.setText(String.valueOf(total));
            
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Los campos de nota deben "
                                                          + "contener valores numericos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila, total;
        //se le asigna el valor de la posici+on de la fila seleccionada de la tabla
        fila = tablaResumen.getSelectedRow();
        
        //se evalúa si es mayor o igual a 0
        if(fila>=0)
            //eliminamos la fila
            dtm.removeRow(fila);
        else
            JOptionPane.showMessageDialog(null, "Selecciona una fila de "
                                                          + "la tabla para eliminar");
        
        //obtenemos el nuevo valor de filas de la tabla, en caso hallamos eliminado alguno
        total = dtm.getRowCount();
        //imprimimos
        txtTotalAlumnos.setText(String.valueOf(total));
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaResumen;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtNotaI;
    private javax.swing.JTextField txtNotaII;
    private javax.swing.JTextField txtNotaIII;
    private javax.swing.JTextField txtTotalAlumnos;
    // End of variables declaration//GEN-END:variables
}
