/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JComboBox;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Matricula2 extends javax.swing.JFrame {
    //crear un model para cada una de las 4 listas
    private DefaultListModel modelo1 = new DefaultListModel();
    private DefaultListModel modelo2 = new DefaultListModel();
    private DefaultListModel modelo3 = new DefaultListModel();
    private DefaultListModel modelo4 = new DefaultListModel();
    
    public Matricula2() {
        initComponents();
        //la variable modelo1 es de para la caja de la lista lstCursosOfertados
        lstCursosOfertados.setModel(modelo1);
        lstCostoO.setModel(modelo2);
        lstCursosEscogidos.setModel(modelo3);
        lstCostoE.setModel(modelo4);
        //Los botones se inhabiliten desde la ejecución de la aplicación
        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
        //Localización dentro de la pantalla y el tamaño del formulario
        setSize(450,400);
        setLocation(250,250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAlumno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboCategoriaCursos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCursosOfertados = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCostoO = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstCursosEscogidos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstCostoE = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboFormaPago = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCostoTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPagoMensual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ALUMNO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 220, -1));

        jLabel2.setText("Categoría de Cursos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        cboCategoriaCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Diseño", "Gráfico", "Diseño Web", "Ofimática", "Lenguajes de Programación", "Sistemas Operativos" }));
        cboCategoriaCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaCursosActionPerformed(evt);
            }
        });
        getContentPane().add(cboCategoriaCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 170, -1));

        jLabel3.setText("Cursos Ofertados");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lstCursosOfertados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosOfertadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCursosOfertados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 110));

        jScrollPane2.setViewportView(lstCostoO);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 70, 110));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel4.setText("Costo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        jLabel5.setText("Cursos Escogidos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        lstCursosEscogidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCursosEscogidosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstCursosEscogidos);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 150, 110));

        jScrollPane4.setViewportView(lstCostoE);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 80, 110));

        jLabel6.setText("Costo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel7.setText("Forma de Pago:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        cboFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Contado", "Crédito" }));
        getContentPane().add(cboFormaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jLabel8.setText("Matrícula");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));
        getContentPane().add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 110, -1));

        jLabel9.setText("Costo Total");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));
        getContentPane().add(txtCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 110, -1));

        jLabel10.setText("Pago Mensual");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));
        getContentPane().add(txtPagoMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlumnoActionPerformed

    private void cboCategoriaCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaCursosActionPerformed
        //variable de memoria, para que almacene el índice actual del Ítem seleccionado 
        int indice;
        indice = cboCategoriaCursos.getSelectedIndex();
        
        switch(indice){
            case 0:
                //modelo1 es lstCursosOfertados  -  modelo2 es lstCursosEscogidos
                modelo1.clear(); modelo2.clear();
                break;
            case 1:
                //primero se limpia y luego se muestran los nombres
                modelo1.clear(); modelo2.clear();
                modelo1.addElement("Corel Draw"); modelo2.addElement("180");
                modelo1.addElement("Photo Shop"); modelo2.addElement("170");
                
                break;
            case 2:
                modelo1.clear(); modelo2.clear();
                modelo1.addElement("Diseño con HTML"); modelo2.addElement("100");
                modelo1.addElement("JavaScript"); modelo2.addElement("120");
                modelo1.addElement("PHP y MySQL"); modelo2.addElement("180");
                modelo1.addElement("ASP .Net"); modelo2.addElement("180");
                break;
            case 3:
                modelo1.clear(); modelo2.clear();
                modelo1.addElement("Word"); modelo2.addElement("120");
                modelo1.addElement("Excel"); modelo2.addElement("130");
                modelo1.addElement("Power"); modelo2.addElement("100");
                modelo1.addElement("Visio"); modelo2.addElement("110");
                break;
            case 4:
                modelo1.clear(); modelo2.clear();
                modelo1.addElement("Visual Basic .Net"); modelo2.addElement("240");
                modelo1.addElement("Visual java"); modelo2.addElement("290");
                modelo1.addElement("Power Builder"); modelo2.addElement("230");
                modelo1.addElement("Visual C# .Net"); modelo2.addElement("220");
                break;
            case 5:
                modelo1.clear(); modelo2.clear();
                modelo1.addElement("Windows Vista"); modelo2.addElement("160");
                modelo1.addElement("Linux"); modelo2.addElement("180");
                break;
        }
    }//GEN-LAST:event_cboCategoriaCursosActionPerformed

    private void lstCursosOfertadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosOfertadosValueChanged
        //recibe el valor del indice del item seleccionado
        int indice = lstCursosOfertados.getSelectedIndex();
        //lo que se seleccione en lsCostosO que tenga el mismo indice que lsCursosOfertados
        lstCostoO.setSelectedIndex(indice);
        //habilitamos el botón btnAgregar
        btnAgregar.setEnabled(true);
    }//GEN-LAST:event_lstCursosOfertadosValueChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String curso, costo;
        int total, i;
        //almacenamos el curso seleccionado
        curso = (String)lstCursosOfertados.getSelectedValue();
        //almacenamos el costo seleccionado
        costo = (String)lstCostoO.getSelectedValue();
        //agregar un item a una caja de lista
        modelo3.addElement(curso);
        modelo4.addElement(costo);
        //inhabilitamos el boton btnAgregar
        btnAgregar.setEnabled(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void lstCursosEscogidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCursosEscogidosValueChanged
        //recibe el valor del indice del item seleccionado
        int indice = lstCursosEscogidos.getSelectedIndex();
        //lo que se seleccione en lsCostosE que tenga el mismo indice que lsCursosEscogidos
        lstCostoE.setSelectedIndex(indice);
        //habilitamos el botón btnEliminar
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_lstCursosEscogidosValueChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int indice = lstCursosEscogidos.getSelectedIndex();
        modelo3.remove(indice);
        modelo4.remove(indice);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //almacena la cantidad de items existentes en la caja de lista lstCursoEscogidos
        int cuenta =  modelo3.size();
        float matricula=0, costoTotal=0, pagoMensual=0;
        
        //obtener los valores de la caja de lista lstCostoE
        for(int i=0; i<cuenta; i++){
            //se suman todos los valores obtenidos
            costoTotal=costoTotal+Float.parseFloat((String)modelo4.elementAt(i));
        }
        
        //averiguamos si las cajas lstCursosEscogidos y lstCostoE tienen items
        if(costoTotal==0){
            JOptionPane.showMessageDialog(null,"Slecciona y agrega al menos un curso");
            //suspende la ejeccucion del programa
            return;
        }
        
     //en los 3 if se calcula el monto de la maatricula aplicando el porcentaje incicado en el enunciado
        if(cuenta==1)
            matricula = costoTotal*0.8f;
        if(cuenta==2)
            matricula = costoTotal*0.6f;
        if(cuenta>=3)
            matricula = costoTotal*0.5f;
        
        //en los 3 if siguientes se evalua si se seleccionó una forma de pago
        if(cboFormaPago.getSelectedItem().equals("<Seleccionar>")){
            JOptionPane.showMessageDialog(null,"Selecciona una forma de pago");
            return;
        }
        if(cboFormaPago.getSelectedItem().equals("Contado")){
            costoTotal = costoTotal*0.09f;
            pagoMensual = 0;
        }
        if(cboFormaPago.getSelectedItem().equals("Crédito")){
            costoTotal = costoTotal*1.1f;
            pagoMensual = costoTotal/4;
        }
        
        txtMatricula.setText(String.valueOf(matricula));
        txtCostoTotal.setText(String.valueOf(costoTotal));
        txtPagoMensual.setText(String.valueOf(pagoMensual));
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtAlumno.setText("");
    /*ponemos el indice 7 ya que dicho indice no existe en la caja, lo que hace que 
      se pierda lo seleccionado*/
        cboCategoriaCursos.setSelectedIndex(7);
        cboFormaPago.setSelectedIndex(7);
        /*limpiar variables del objeto modelo1,2,3,4 y a la vez a los objetos que están en ellas*/
        modelo1.clear();
        modelo2.clear();
        modelo3.clear();
        modelo4.clear();
        txtMatricula.setText("");
        txtCostoTotal.setText("");
        txtPagoMensual.setText("");
        //Ponemos el cursos del puse aquí
        txtAlumno.requestFocus();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matricula2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matricula2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matricula2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matricula2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matricula2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cboCategoriaCursos;
    private javax.swing.JComboBox<String> cboFormaPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstCostoE;
    private javax.swing.JList<String> lstCostoO;
    private javax.swing.JList<String> lstCursosEscogidos;
    private javax.swing.JList<String> lstCursosOfertados;
    private javax.swing.JTextField txtAlumno;
    private javax.swing.JTextField txtCostoTotal;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtPagoMensual;
    // End of variables declaration//GEN-END:variables
}
