/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JPanel_JScrollPanel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmPelicula extends javax.swing.JFrame {
    //variable memoria del tipo DefaultTableModel
    DefaultTableModel dtm = new DefaultTableModel();
    
    public frmPelicula() {
        initComponents();
        //inicializamos los títulos de las columnas
        String titulos[]={"Título de la Película","Categoría","Duración(min)"
                          ,"Actor Principal"};
        //se define las columnas con sus respectivos titulos
        dtm.setColumnIdentifiers(titulos);
        //se vincula el modelo
        tablaResumen.setModel(dtm);
        
        /*ihnabilitamos los objetos para que al ejecutar solo de
          pueda NUEVO, ELIMINAR Y CERRAR*/
        txtPelicula.setEnabled(false);
        jPanel1.setEnabled(false);
        txtDuracion.setEnabled(false);
        txtActor.setEnabled(false);
        btnAgregar.setEnabled(false);
        btnNuevo.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtPelicula = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rbComedia = new javax.swing.JRadioButton();
        rbAccion = new javax.swing.JRadioButton();
        rbDibujos = new javax.swing.JRadioButton();
        rbDrama = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaResumen = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtActor = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPeliculas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PELICULA:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        getContentPane().add(txtPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 210, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Categorías de Películas"));

        buttonGroup1.add(rbComedia);
        rbComedia.setText("Comedia");
        rbComedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComediaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAccion);
        rbAccion.setText("Acción");

        buttonGroup1.add(rbDibujos);
        rbDibujos.setText("Dibujos Animados");

        buttonGroup1.add(rbDrama);
        rbDrama.setText("Drama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbComedia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAccion)
                .addGap(18, 18, 18)
                .addComponent(rbDibujos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDrama)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbComedia)
                    .addComponent(rbAccion)
                    .addComponent(rbDibujos)
                    .addComponent(rbDrama))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 370, 60));

        tablaResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaResumen);

        jScrollPane1.setViewportView(jScrollPane2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 480, 200));

        jLabel2.setText("DURACIÓN:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        getContentPane().add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, -1));

        jLabel3.setText("min");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel4.setText("ACTOR PRINCIPAL:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));
        getContentPane().add(txtActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 220, -1));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel5.setText("Total de películas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));
        getContentPane().add(txtTotalPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 500, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbComediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbComediaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        //HABILITAMOS TODO LO INHABILITADO E INHABILITAMOS NUEVO
        txtPelicula.setEnabled(true);
        jPanel1.setEnabled(true);
        txtDuracion.setEnabled(true);
        txtActor.setEnabled(true);
        //limpiarlo en caso este algo escrito
        txtPelicula.setText("");
        //al presionar en NUEVO se va a seleccionar Comedia por defecto
        rbComedia.setSelected(true);
        //limpiarlo en caso este algo 
        txtDuracion.setText("");
        txtActor.setText("");
        //habilitamos agregar
        btnAgregar.setEnabled(true);
        //inhabilitamos NUEVO
        btnNuevo.setEnabled(false);
        //El curso se dirige aquí al presionar NUEVO
        txtPelicula.requestFocus();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String datos[] = new String[4];
        int totalPeliculas;
        
        //asignamos la posicion 0 para que solo aparezcan nombres de Pelis
        datos[0] = txtPelicula.getText();
        //Así se hace para la asignacion de un radio button
        if(rbComedia.isSelected())
            datos[1] = "Comedia";
        if(rbAccion.isSelected())
            datos[1] = "Acción";
        if(rbDibujos.isSelected())
            datos[1] = "Dibujos Animados";
        if(rbDrama.isSelected())
            datos[1] = "Drama";
        //asignamos las demás positions de manera normal
        datos[2] = txtDuracion.getText();
        datos[3] = txtActor.getText();
        
        /*agregamos una fila en el objeto JTable con los datos contenidos
          en el arreglo datos*/
        dtm.addRow(datos);
        
        //Hallamos la cantidad de filas de datos que tiene el objeto JTable
        totalPeliculas = dtm.getRowCount();
        //imprimimos la cantidad de filas
        txtTotalPeliculas.setText(String.valueOf(totalPeliculas));
        
        //Habilitamos NUEVO ya que se agrego uno nuevo, seria lo más lógico
        btnNuevo.setEnabled(true);
    /*Inhabilitamos AGREGAR ya que ya agregamos lo que está escrito y no 
      hay nada nuevo por agregar*/
        btnAgregar.setEnabled(false);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila, totalPeliculas;
        //se le asigna el valor de la posición de la fila seleccionada
        fila = tablaResumen.getSelectedRow();
        /*si hay algo seleccionado se elimina la fila, ya que inicia desde 0
          el array de datos*/
        if(fila>=0)
            dtm.removeRow(fila);
        else 
            JOptionPane.showMessageDialog(null,"Selecciona una "
                                       + "fila de la Tabla  para eliminar");
        
        //Actualizamos la cantidad de filas que hay en caso se borraron
        totalPeliculas = dtm.getRowCount();
        //imprmimos la cantidad de filas
        txtTotalPeliculas.setText(String.valueOf(totalPeliculas));
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbAccion;
    private javax.swing.JRadioButton rbComedia;
    private javax.swing.JRadioButton rbDibujos;
    private javax.swing.JRadioButton rbDrama;
    private javax.swing.JTable tablaResumen;
    private javax.swing.JTextField txtActor;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtPelicula;
    private javax.swing.JTextField txtTotalPeliculas;
    // End of variables declaration//GEN-END:variables
}
