/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JRadioButton_JCheckBox;

/**
 *
 * @author USUARIO
 */
public class Aplicacion2 extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion2
     */
    public Aplicacion2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtSueldoBasico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbSecundaria = new javax.swing.JRadioButton();
        rbUniversitaria = new javax.swing.JRadioButton();
        rbMaestria = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbContratado = new javax.swing.JRadioButton();
        rbNombrado = new javax.swing.JRadioButton();
        rbSNP = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        chkCasado = new javax.swing.JCheckBox();
        chkHijos = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBonificacion = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        txtSueldoNeto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingresar sueldo basico:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, -1, -1));
        getContentPane().add(txtSueldoBasico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 90, -1));

        jLabel2.setText("Grado de instruccion:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        buttonGroup1.add(rbSecundaria);
        rbSecundaria.setText("Secundaria");
        rbSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSecundariaActionPerformed(evt);
            }
        });
        getContentPane().add(rbSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        buttonGroup1.add(rbUniversitaria);
        rbUniversitaria.setText("Universitaria");
        getContentPane().add(rbUniversitaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        buttonGroup1.add(rbMaestria);
        rbMaestria.setText("Maestria");
        getContentPane().add(rbMaestria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel3.setText("Condicion laboral:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        buttonGroup2.add(rbContratado);
        rbContratado.setText("Contratado");
        getContentPane().add(rbContratado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        buttonGroup2.add(rbNombrado);
        rbNombrado.setText("Nombrado");
        getContentPane().add(rbNombrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        buttonGroup2.add(rbSNP);
        rbSNP.setText("Servicios no personales");
        getContentPane().add(rbSNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 360, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 360, -1));

        chkCasado.setText("Casado");
        getContentPane().add(chkCasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        chkHijos.setText("Hijos");
        getContentPane().add(chkHijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        jLabel4.setText("Bonificacion:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel5.setText("Descuento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel6.setText("Sueldo Neto:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        getContentPane().add(txtBonificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 90, -1));
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 90, -1));
        getContentPane().add(txtSueldoNeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSecundariaActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double bonificacion= 0.0, sueldoBasico, descuento, sueldoNeto, sueldoBruto;
        
        sueldoBasico = Double.parseDouble(txtSueldoBasico.getText());
        
        //Grado de instruccion
        if(rbSecundaria.isSelected())
            bonificacion = sueldoBasico*0.05;
        if(rbUniversitaria.isSelected())
            bonificacion = sueldoBasico*0.12;
        if(rbMaestria.isSelected())
            bonificacion = sueldoBasico*0.18;
        //Condición laboral
        if(rbContratado.isSelected())
            bonificacion = bonificacion+sueldoBasico*0.04;
        if(rbNombrado.isSelected())
            bonificacion = bonificacion+sueldoBasico*0.01;
        if(rbSNP.isSelected())
            bonificacion = bonificacion+sueldoBasico*0.05;
        
        if(!(chkCasado.isSelected()))
            bonificacion = bonificacion+sueldoBasico*0.03;
        if(chkHijos.isSelected())
            bonificacion = bonificacion+sueldoBasico*0.06;
        
        sueldoBruto = sueldoBasico+bonificacion;
        descuento = sueldoBruto*0.11;
        sueldoNeto = sueldoBruto - descuento;
        
        txtBonificacion.setText(String.valueOf(bonificacion));
        txtDescuento.setText(String.valueOf(descuento));
        txtSueldoNeto.setText(String.valueOf(sueldoNeto));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtSueldoBasico.setText("");
        txtBonificacion.setText("");
        txtDescuento.setText("");
        txtSueldoNeto.setText("");
        txtSueldoBasico.requestFocus();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox chkCasado;
    private javax.swing.JCheckBox chkHijos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rbContratado;
    private javax.swing.JRadioButton rbMaestria;
    private javax.swing.JRadioButton rbNombrado;
    private javax.swing.JRadioButton rbSNP;
    private javax.swing.JRadioButton rbSecundaria;
    private javax.swing.JRadioButton rbUniversitaria;
    private javax.swing.JTextField txtBonificacion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtSueldoBasico;
    private javax.swing.JTextField txtSueldoNeto;
    // End of variables declaration//GEN-END:variables
}
