/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JRadioButton_JCheckBox;

/**
 *
 * @author USUARIO
 */
public class CostoArtefacto extends javax.swing.JFrame {

    /**
     * Creates new form CostoArtefacto
     */
    public CostoArtefacto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rbAudio = new javax.swing.JRadioButton();
        rbVideo = new javax.swing.JRadioButton();
        rbLinea = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        chkContado = new javax.swing.JCheckBox();
        btnCalcular = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        txtIncremento = new javax.swing.JTextField();
        txtIgv = new javax.swing.JTextField();
        txtMPagar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("COSTO DEL ARTEFACTO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 90, -1));

        jLabel2.setText("Tipos de Artefactos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        buttonGroup1.add(rbAudio);
        rbAudio.setText("Audio");
        rbAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAudioActionPerformed(evt);
            }
        });
        getContentPane().add(rbAudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        buttonGroup1.add(rbVideo);
        rbVideo.setText("Video");
        getContentPane().add(rbVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        buttonGroup1.add(rbLinea);
        rbLinea.setText("Linea Blanca");
        getContentPane().add(rbLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel3.setText("Forma de Pago:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        chkContado.setText("Contado");
        getContentPane().add(chkContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabel4.setText("Descuento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel5.setText("Incremento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jLabel6.setText("Monto de IGV:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel7.setText("Monto a Pagar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));
        getContentPane().add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 120, -1));
        getContentPane().add(txtIncremento, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 120, -1));
        getContentPane().add(txtIgv, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 120, -1));
        getContentPane().add(txtMPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAudioActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double costo, descuento=0 , incremento=0, igv, mPagar;
        
        costo = Double.parseDouble(txtCosto.getText());
        
        if (chkContado.isSelected()){
            if (rbAudio.isSelected())
                descuento = costo*0.06;
            if (rbVideo.isSelected())
                descuento = costo*0.08;
            if (rbLinea.isSelected())
                descuento = costo*0.05;
        } else {
            if (rbAudio.isSelected())
                incremento = costo*0.07;
            if (rbVideo.isSelected())
                incremento = costo*0.09;
            if (rbLinea.isSelected())
                incremento = costo*0.10;
        }
        
        igv = (costo-descuento+incremento)*0.19;
        mPagar = (costo-descuento+incremento)+igv;
        
        txtDescuento.setText(String.valueOf(descuento));
        txtIncremento.setText(String.valueOf(incremento));
        txtIgv.setText(String.valueOf(igv));
        txtMPagar.setText(String.valueOf(mPagar));
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        txtCosto.setText("");
        txtDescuento.setText("");
        txtIncremento.setText("");
        txtIgv.setText("");
        txtMPagar.setText("");
        rbAudio.setSelected(false);
        rbLinea.setSelected(false);
        rbVideo.setSelected(false);
        chkContado.setSelected(false);
        txtCosto.requestFocus();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CostoArtefacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CostoArtefacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CostoArtefacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CostoArtefacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CostoArtefacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkContado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rbAudio;
    private javax.swing.JRadioButton rbLinea;
    private javax.swing.JRadioButton rbVideo;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtIgv;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextField txtMPagar;
    // End of variables declaration//GEN-END:variables
}
